const PRODUCTS = [
  { id:1,  name:'Golden Hour Serum',      sub:'Skincare',   cat:'skincare',  price:3499, old:4200, icon:'🌸', badge:'Best Seller', rating:5, reviews:128,
    desc:'A luxurious serum infused with 24k gold particles, hyaluronic acid, and our proprietary botanical complex. Transforms skin overnight for visible radiance by morning.',
    ingredients:'Water, Niacinamide, 24k Gold, Hyaluronic Acid, Rose Hip Oil, Peptide Complex, Aloe Vera Extract.'},
  { id:2,  name:'Rose Velvet Cream',       sub:'Skincare',   cat:'skincare',  price:2299, old:null, icon:'🌺', badge:null,          rating:4, reviews:89,
    desc:'Rich velvety moisturiser with rose hip oil and shea butter. Deeply nourishing without feeling heavy. Perfect for dry and combination skin.',
    ingredients:'Shea Butter, Rose Hip Oil, Glycerin, Squalane, Ceramides, Rose Extract, Vitamin E.'},
  { id:3,  name:'Midnight Repair Oil',     sub:'Skincare',   cat:'skincare',  price:4199, old:5000, icon:'✦',  badge:'New',         rating:5, reviews:54,
    desc:'Potent facial oil blend with squalane, rosehip and sea buckthorn. Repairs skin barrier and reduces fine lines while you sleep.',
    ingredients:'Squalane, Rosehip Oil, Sea Buckthorn, Bakuchiol, Chia Seed Oil, Vitamin C Ester.'},
  { id:4,  name:'Pearl Glow Toner',        sub:'Skincare',   cat:'skincare',  price:1899, old:null, icon:'💎', badge:null,          rating:4, reviews:203,
    desc:'Brightening essence with pearl extract and vitamin C. Balances pH and preps skin for maximum absorption of serums and moisturisers.',
    ingredients:'Pearl Extract, Vitamin C, Niacinamide, Panthenol, Willow Bark, Allantoin.'},
  { id:5,  name:'Crystal Eye Cream',       sub:'Skincare',   cat:'skincare',  price:3299, old:null, icon:'💧', badge:null,          rating:5, reviews:76,
    desc:'Powerful peptide eye cream with caffeine and ceramides. Visibly reduces dark circles, puffiness, and fine lines within 4 weeks.',
    ingredients:'Peptide Complex, Caffeine, Ceramides, Retinol, Collagen, Vitamin K.'},
  { id:6,  name:'Sun Veil SPF 50',         sub:'Skincare',   cat:'skincare',  price:1799, old:2100, icon:'☀️', badge:'Essential',   rating:4, reviews:341,
    desc:'Ultra-lightweight sunscreen that doubles as a primer. Zero white cast. Broad-spectrum SPF 50 PA++++. Perfect under makeup.',
    ingredients:'Zinc Oxide, Tinosorb, Niacinamide, Hyaluronic Acid, Glycerin, Silica.'},
  { id:7,  name:'Velvet Lip Elixir',       sub:'Makeup',     cat:'makeup',    price:1299, old:1600, icon:'💋', badge:'Sale',        rating:4, reviews:178,
    desc:'Long-lasting satin lipstick enriched with argan oil and vitamin E. Hydrating, pigmented, and available in 12 gorgeous shades.',
    ingredients:'Argan Oil, Vitamin E, Castor Oil, Jojoba, Beeswax, Candelilla Wax.'},
  { id:8,  name:'Celestial Foundation',   sub:'Makeup',     cat:'makeup',    price:2799, old:null, icon:'🌟', badge:null,          rating:5, reviews:95,
    desc:'Buildable coverage foundation with a natural luminous finish. SPF 30+. 30 shades for every skin tone. Stays fresh for 16 hours.',
    ingredients:'Water, Cyclopentasiloxane, Titanium Dioxide, Niacinamide, SPF 30 filters, Hyaluronic Acid.'},
  { id:9,  name:'Sculpt & Define Palette',sub:'Makeup',     cat:'makeup',    price:2199, old:2600, icon:'🎨', badge:'Sale',        rating:4, reviews:62,
    desc:'An 8-pan contour palette with matte bronzers, shimmers, and highlighters. Buildable pigment for every look, from no-makeup makeup to full glam.',
    ingredients:'Talc, Mica, Iron Oxides, Bismuth Oxychloride, Dimethicone, Tocopheryl Acetate.'},
  { id:10, name:'Ambre Soir Parfum',       sub:'Fragrance',  cat:'fragrance', price:6499, old:null, icon:'🌙', badge:'Luxury',      rating:5, reviews:47,
    desc:'A sophisticated evening fragrance. Notes of amber, oud, and vanilla with a warm, sensual dry down. Lasts 12+ hours on skin.',
    ingredients:'Alcohol Denat., Amber, Oud, Vanilla, Bergamot, Sandalwood, Musk.'},
  { id:11, name:'Garden Bloom EDT',        sub:'Fragrance',  cat:'fragrance', price:3999, old:4800, icon:'🌸', badge:null,          rating:4, reviews:88,
    desc:'A light feminine floral scent opening with bergamot and peony, settling into a white musk base. Fresh and long-lasting.',
    ingredients:'Alcohol Denat., Bergamot, Peony Extract, Jasmine, Rose, White Musk, Sandalwood.'},
  { id:12, name:'Silk Body Butter',        sub:'Body Care',  cat:'body',      price:1599, old:null, icon:'🧴', badge:null,          rating:4, reviews:134,
    desc:'Rich body butter infused with shea, mango, and kokum butter. Melts into skin instantly leaving it silky soft and scented for 24 hours.',
    ingredients:'Shea Butter, Mango Butter, Kokum Butter, Argan Oil, Vitamin E, Lavender Essential Oil.'},
];
